# Codecov configuration
# https://docs.codecov.io/docs/codecovyml-reference

coverage:
  # Coverage precision (number of decimal places)
  precision: 2
  round: down
  
  # Coverage range colors
  range: "70...100"
  
  status:
    project:
      default:
        # Project coverage must be at least 70%
        target: 70%
        # Allow coverage to drop by 2% without failing
        threshold: 2%
        # Don't fail the CI if coverage targets aren't met
        informational: true
        
    patch:
      default:
        # New code must have at least 80% coverage
        target: 80%
        # Don't fail the CI if coverage targets aren't met
        informational: true
        
    changes: false

# Files to ignore
ignore:
  - "examples/**/*"
  - "tests/**/*"
  - "benches/**/*"
  - "**/tests.rs"
  - "**/test_*.rs"
  - "**/*_test.rs"

# Comments on pull requests
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  
# Component configuration for workspace crates
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%
        informational: true
        
  individual_components:
    - component_id: langfuse-client-base
      name: Base Client
      paths:
        - langfuse-client-base/**
        
    - component_id: langfuse-ergonomic
      name: Ergonomic Client
      paths:
        - langfuse-ergonomic/**