name: cargo-deny

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run weekly to catch new advisories
    - cron: '0 0 * * MON'

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install cargo-deny
        run: |
          wget https://github.com/EmbarkStudios/cargo-deny/releases/download/0.16.2/cargo-deny-0.16.2-x86_64-unknown-linux-musl.tar.gz
          tar -xzf cargo-deny-0.16.2-x86_64-unknown-linux-musl.tar.gz
          sudo mv cargo-deny-0.16.2-x86_64-unknown-linux-musl/cargo-deny /usr/local/bin/
      
      - name: Check advisories
        run: cargo deny check advisories
      
      - name: Check bans
        run: cargo deny check bans
      
      - name: Check licenses
        run: cargo deny check licenses
      
      - name: Check sources
        run: cargo deny check sources